# Generated by Django 6.0 on 2025-12-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('isCompleted', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
